// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsuNPPDxvBGN6LtYIlqQ1JDzcXcLXo2-8',
    appId: '1:411882295751:web:05e0b0b7032216fe6509e2',
    messagingSenderId: '411882295751',
    projectId: 'gitpu-947eb',
    authDomain: 'gitpu-947eb.firebaseapp.com',
    storageBucket: 'gitpu-947eb.firebasestorage.app',
    measurementId: 'G-XCXMHY8T2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt9jcHExCOlhNZy-H4T6dnHcdmbRoEWqw',
    appId: '1:411882295751:android:b3fe549a538ef9cf6509e2',
    messagingSenderId: '411882295751',
    projectId: 'gitpu-947eb',
    storageBucket: 'gitpu-947eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC37ifAuOzJfbGRU5RGZE4TYDISWU7sW4',
    appId: '1:411882295751:ios:2fc2ff691e42d92c6509e2',
    messagingSenderId: '411882295751',
    projectId: 'gitpu-947eb',
    storageBucket: 'gitpu-947eb.firebasestorage.app',
    iosBundleId: 'com.example.gitpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC37ifAuOzJfbGRU5RGZE4TYDISWU7sW4',
    appId: '1:411882295751:ios:2fc2ff691e42d92c6509e2',
    messagingSenderId: '411882295751',
    projectId: 'gitpu-947eb',
    storageBucket: 'gitpu-947eb.firebasestorage.app',
    iosBundleId: 'com.example.gitpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsuNPPDxvBGN6LtYIlqQ1JDzcXcLXo2-8',
    appId: '1:411882295751:web:7f49d8eff86d5e546509e2',
    messagingSenderId: '411882295751',
    projectId: 'gitpu-947eb',
    authDomain: 'gitpu-947eb.firebaseapp.com',
    storageBucket: 'gitpu-947eb.firebasestorage.app',
    measurementId: 'G-34EBG7TFC5',
  );
}
